config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, :readings, :reports

  root 'home#index'

end

app/models/reading.rb
class Reading < ActiveRecord::Base
  # Each reading belongs to the user that created it
  belongs_to :user

  # Quota limits the number of readings one can submit per day
  validate :reading_quota, :on => :create

  # record glucose level, ensure it is a positive integer
  validates :glucose_level, presence: true,
            numericality: { only_integer: true, greater_than_or_equal_to: 0,
                            :message => "Readings must be a positive integer. Please try again."}
  # Ensure current_user is accessible
  mattr_accessor :current_user

  # default scope for readings arranges them in ascending order
  default_scope { order(created_at: :asc) }

  scope :within_dates, ->(d1, d2) {where(:created_on => d1..d2)}

  private
    # Checks that users have not created 4 readings 'today' yet.
    # The limit for daily new readings is no more than 4. See 'Sweety.Requirements.txt'
    def reading_quota
      if current_user && current_user.readings.today.count >= 4
        errors.add(:base, "Exceeds daily limit for blood glucose readings. Please try again tomorrow.")
      end
    end
end

app/models/report.rb
class Report < ActiveRecord::Base

  mattr_accessor :current_user
  belongs_to :user
  has_many :readings, through: :user

  # Setup json to be sent to Highcharts
  def json
    @json = ""
    # Time created must be converted to milliseconds for JS so multiply by 1000
    readings_subset.each do |val|
      @json = @json + "[#{val.created_at.to_i*1000}, #{val.glucose_level}],"
    end
    @json.to_s.chomp(',')
  end

  # Average of glucose readings that fall within date range
  def average_glucose
    readings_subset.average(:glucose_level)
  end

  # Maximum of glucose readings that fall within date range
  def max_glucose
    readings_subset.maximum(:glucose_level)
  end

  # Minimum of glucose readings that fall within date range
  def min_glucose
    readings_subset.minimum(:glucose_level)
  end

  # Limit glucose readings to only readings that fall within date range
  def readings_subset
    readings.within_dates(start_date, end_date)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Reports all belong to the user that created them
  has_many :reports

  # Readings all belong to the user that created them
  has_many :readings do

    # Returns readings created today by user
    def today
      where(:created_at => (Time.zone.now.beginning_of_day..Time.zone.now))
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_current_user

  def set_current_user
    Reading.current_user = current_user
  end

  protected

  # Sanitize added parameters for Devise User here
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/readings_controller.rb
class ReadingsController < ApplicationController
  # Require user login before accessing any readings
  before_action :authenticate_user!

  def index
    @readings = current_user.readings
  end

  def new
    @reading = Reading.new
  end

  def create
    @reading = Reading.new(reading_params)
    @reading.user = current_user

    if @reading.save
      redirect_to @reading
    else
      render 'new'
    end
  end

  def show
    @reading = Reading.find(params[:id])
  end
end

private
  def reading_params
    params.require(:reading).permit(:glucose_level, :current_user)
  end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  # Require user login before accessing any reports
  before_action :authenticate_user!

  def index
    @reports = current_user.reports
  end

  def new
    @report = Report.new
  end

  def create
    @report = Report.new(report_params)
    @report.user = current_user

    if @report.save
      redirect_to @report
    else
      render 'new'
    end
  end

  def show
    @report = Report.find(params[:id])
  end
end

private
  def report_params
    params.require(:report).permit(:start_date, :end_date, :current_user)
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/readings_helper.rb
module ReadingsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
  # Show Report details on reports page
  def details(report)
    if report.start_date === report.end_date
      render 'date_report'
    else
      render 'range_report'
    end
  end

  # Place hidden forms on page to allow default reports to be dynamic
  def report_form(start_date, title)
    @start_d = start_date
    @title = title
    render 'default_report'
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="jumbotron">
  <div class="container">
    <h2>Welcome to Sweety!</h2>
    <h4>This is your personal blood glucose level app!</h4>
    <% if user_signed_in? %>
      <%= link_to 'Enter new blood glucose reading', new_reading_path, class: 'btn btn-success' %>
      <p><%= link_to 'View History', readings_path, class: 'btn btn-primary'  %></p>
    <% else %>
      <p>Please register to begin:</p>
      <p><%= link_to 'Register', new_user_registration_path, class: 'btn btn-primary btn-lg' %></p>
      <p><%= link_to 'Log In', new_user_session_path, class: 'btn btn-primary btn-lg', id: 'login' %></p>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sweety</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse">
    <div class="container">
      <div class="navbar-header">
        <%= link_to 'Sweety', root_path, class: 'navbar-brand' %>
      </div>
      <div id="navbar">
        <ul class="nav navbar-nav">
          <li><%= link_to 'Home', root_path %></li>
          <li><%= link_to 'Readings', readings_path %></li>
          <li><%= link_to 'Reports', reports_path %></li>
        </ul>
        <ul class="nav navbar-nav pull-right">
          <% if user_signed_in? %>
              <li><%= link_to "#{current_user.name}", edit_user_registration_path %></li>
              <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
          <% else %>
              <li><%= link_to 'Log In', new_user_session_path, id: 'nav-login' %></li>
              <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

  <div class="container">
    <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>">
          <%= value %>
        </div>
    <% end %>
  </div>

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/readings/index.html.erb
<h1>Blood Glucose Level History</h1>

<%= link_to 'Enter new blood glucose reading', new_reading_path, class: 'btn btn-success' %>

<table>
  <tr>
    <th>Glucose Level (mg/dL)</th>
    <th>Date Created</th>
  </tr>
   
  <% @readings.each do |reading| %>
    <tr>
      <td><%= reading.glucose_level %></td>
      <td><%= reading.created_at.strftime("%A, %B %d, %Y") %></td>
    </tr>
  <% end %>
</table>

app/views/readings/new.html.erb
<%= form_for :reading, url: readings_path do |f| %>

  <% if @reading.errors.any? %>
    <div id="error-explanation">
      <h2>
        <%= pluralize(@reading.errors.count, "error") %> prohibited this reading from being saved
      </h2>
      <ul>
        <% @reading.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <h4><%= f.label :glucose_level, "Glucose level (mg/dL)" %></h4>
    <%= f.text_field :glucose_level, class: 'form-control', autofocus: true %>
  </div>

  <div class="actions">
    <%= f.submit "Save", class: 'btn btn-success' %>
    <%= link_to "Cancel", :back, class: 'btn btn-default'  %>
  </div>
<% end %>

app/views/readings/show.html.erb
<h4>
  <strong>Blood Glucose Level Reading:</strong>
  <%= @reading.glucose_level %> (mg/dL)
</h4>
<h4>Date recorded:
  <%= @reading.created_at.strftime("%A, %B %d, %Y") %>
</h4>
<br/>
<p>
  <%= link_to 'Enter new blood glucose reading', new_reading_path, class: 'btn btn-success' %>
  <%= link_to 'View History', readings_path, class: 'btn btn-primary'  %>
</p>

app/views/reports/_chart.html.erb
<script type="text/javascript" charset="utf-8">
  $(function () {
    $('#range-chart').highcharts({
      title: {
        text: 'Blood Glucose Level',
        x: -20 //center
      },
      subtitle: {
        text: '<%= @report.start_date.strftime("%B %d, %Y")%> - <%= @report.end_date.strftime("%B %d, %Y")%>',
        x: -20
      },
      xAxis: {
        type: 'datetime',
        dateTimeLabelFormats: {
          millisecond: '%H:%M',
          second: '%H:%M',
          minute: '%H:%M',
          hour: '%H:%M',
          day: '%b %e',
          week: '%b %e',
          month: '%b %e',
          year: '%b'
        },
        title: {
          text: 'Date'
        }
      },
        yAxis: {
          title: {
            text: 'Blood Glucose Level (mg/dL)'
          },
          plotLines: [{
            value: 0,
            width: 2,
            color: '#808080'
          }]
      },
      tooltip: {
        valueSuffix: ' mg/dL'
      },
      legend: {
        enabled: false
      },
      series: [{
        name: 'Blood Glucose Level',
        data: [<%= @report.json %>]
      }]
    });
  });
</script>

app/views/reports/_date_report.html.erb
<h2>Blood Glucose Level Report
  <small><%= @report.start_date.strftime("%A, %B %d, %Y") %></small>
</h2>
<br />

app/views/reports/_default_report.html.erb
<%= form_for :report, url: reports_path do |f| %>

    <%= f.hidden_field :start_date, value: @start_d %>
    <%= f.hidden_field :end_date, value: Date.today %>

    <%= f.submit "#{@title}", class: 'btn btn-success' %>

<% end %>

app/views/reports/_range_report.html.erb
<h2>Blood Glucose Level Report <small><%= @report.start_date.strftime("%B %d, %Y")%> - <%= @report.end_date.strftime("%B %d, %Y")%></small></h2>
<div id="range-chart" class="chart"></div>
<%= render 'chart' %>

app/views/reports/_readings_list.html.erb
<br/>
<h4>Readings</h4>
<table>
  <tr>
    <th>Glucose Level (mg/dL)</th>
    <th>Date Created</th>
  </tr>
  <% @report.readings_subset.each do |reading| %>
    <tr>
      <td><%= reading.glucose_level %></td>
      <td><%= reading.created_at.strftime("%A, %B %d, %Y") %></td>
    </tr>
  <% end %>
</table>

app/views/reports/index.html.erb
<h1>Report History</h1>

<div class="navbar-form navbar-left reports">
  <h3>Create New Report</h3>
  <%= report_form(Date.today, "Today's Report") %>
  <%= link_to 'Last Month report', new_report_path, class: 'btn btn-success' %>
  <%= report_form(Date.today.beginning_of_month, 'Month-To-Date Report') %>
  <%= link_to 'Create New Report', new_report_path, class: 'btn btn-primary' %>
</div>

<div>
  <h3>Recent Reports</h3>
  <table>
    <tr>
      <th>From</th>
      <th>To</th>
    </tr>
    <% @reports.first(5).each do |report| %>
      <tr>
        <td><%= report.start_date.strftime("%A, %B %d, %Y") %></td>
        <td><%= report.end_date.strftime("%A, %B %d, %Y") %></td>
        <td><%= link_to "View Report", report, class: 'btn btn-primary'  %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/reports/new.html.erb
<h4>New Glucose Report</h4>

<%= form_for :report, url: reports_path do |f| %>

  <div class="form-group">
    <%= f.label :start_date %><br>
    <%= f.date_select :start_date, class: 'form-control', :order => [:day, :month, :year], selected: 1.month.ago %>
  </div>

  <div class="form-group">
    <%= f.label :end_date %><br>
    <%= f.date_select :end_date, class: 'form-control', :order => [:day, :month, :year] %>
  </div>

  <div class="actions">
    <%= f.submit "Go!", class: 'btn btn-success' %>
    <%= link_to "Cancel", :back, class: 'btn btn-default'  %>
  </div>

<% end %>

app/views/reports/show.html.erb
<h4><%= link_to "Back", :back, class: 'btn btn-default' %></h4>

<%= details(@report) %>

<h4>Details</h4>
<table>
  <tr>
    <th>Average</th>
    <td><%= @report.average_glucose %></td>
  </tr>
  <tr>
    <th>Maximum</th>
    <td><%= @report.max_glucose %></td>
  </tr>
  <tr>
    <th>Minimum</th>
    <td><%= @report.min_glucose %></td>
  </tr>
</table>

<%= render 'readings_list' %>